(function(l){var g=window.AmazonUIPageJS||window.P,h=g._namespace||g.attributeErrors,e=h?h("DetailPageSisserouAssets",""):g;e.guardFatal?e.guardFatal(l)(e,window):e.execute(function(){l(e,window)})})(function(l,g,h){l.when("A","a-dropdown","a-button","ready").execute(function(e,l,h){function F(){function c(c,d,e,g){return function(){var k=l.getSelect(c),h=k.val();h&&(h=a("\x3ctextarea /\x3e").html(h).text(),a.ajax({type:"POST",url:"/gp/product/features/aloha-ppd/udp-ajax-handler/sisserou-report.html",
data:{channelId:u[v],gameId:m.gameId,reportType:d,reportReason:encodeURI(h)}}),G.button[e].hide(),f.report[g].removeClass(b.aok.hidden),k.update({status:"disabled"}))}}e.declarative("sisserouSettings","click",function(){w=!1;f.settings.toggleClass(b.aok.hidden);f.report.menu.removeClass(b.aok.hidden);f.report.streamerMenu.addClass(b.aok.hidden);f.report.playbackMenu.addClass(b.aok.hidden)});e.declarative("toggleReportPlayback","click",function(){w=!0;f.report.menu.addClass(b.aok.hidden);f.report.streamerMenu.addClass(b.aok.hidden);
f.report.playbackMenu.removeClass(b.aok.hidden)});e.declarative("toggleReportStreamer","click",function(){w=!0;f.report.menu.addClass(b.aok.hidden);f.report.streamerMenu.removeClass(b.aok.hidden);f.report.playbackMenu.addClass(b.aok.hidden)});e.declarative("backToSettings","click",function(){w=!1;f.report.menu.removeClass(b.aok.hidden);f.report.streamerMenu.addClass(b.aok.hidden);f.report.playbackMenu.addClass(b.aok.hidden)});f.button.playbackReportSubmit.click(c(A.playbackReportDropdown,"PLAYBACK_REPORT",
"playbackReportSubmit","playbackConfirmation"));f.button.streamerReportSubmit.click(c(A.streamerReportDropdown,"STREAMER_REPORT","streamerReportSubmit","streamerConfirmation"))}function H(){var c=I();J(c);K(c);L(c);F();a(g).resize(e.debounce(B,n.LARGE));k("HeaderRendered",!1);e.declarative("toggleSisserou","click",e.debounce(function(){B();y||d.contentWarning.toggleClass(b.aok.hidden);x=!0;d.sisserou.expander.hasClass(b.icons.collapse)?(c.pause(),C(!0,c),d.button.volume.addClass(b.icons.mute).removeClass(b.icons.volume),
d.noStreamerMessage.addClass(b.aok.hidden),x=!1):z?d.noStreamerMessage.removeClass(b.aok.hidden):y&&c.play();d.sisserou.expander.toggleClass(b.icons.expand).toggleClass(b.icons.collapse);d.sisserou.player.toggleClass(b.aok.hidden);d.watchPrompt.html(d.watchPrompt.data(x?"close":"open"));d.eventHandler.toggleClass(b.aok.hidden);k(x?"HeaderOpened":"HeaderClosed",!1)},n.MEDIUM))}function L(c){e.declarative("sisserouPointerEvents","mouseenter mouseleave",function(a){c.isPaused()||p||w||(a="mouseleave"===
a.type,d.stream.info.toggleClass(b.aok.hidden,a),d.stream.controls.toggleClass(b.aok.hidden,a),f.settings.addClass(b.aok.hidden))});e.declarative("sisserouPlayPause","click",e.debounce(function(){c.isPaused()?c.play():c.pause()},n.MEDIUM))}function I(){var c=!1,a=new q.Player(M.twitchPlayerContainer,{width:"100%",height:"100%",channel:u[v],autoplay:!1,muted:!0,showMature:!1,player:"amazon_product_page",allowfullscreen:!1});a.addEventListener(q.Player.PLAY,function(){c||(d.stream.name.text(a.getChannel()),
c=!0);r=Date.now();k("Play",!0)});a.addEventListener(q.Player.PLAYING,function(){d.button.play.addClass(b.icons.pause).removeClass(b.icons.play);d.eventHandler.removeClass(b.pointerEvents.none)});if(g.ue&&g.ue.onunload&&"function"===typeof g.ue.onunload)g.ue.onunload(function(){(t=r?Date.now()-r+t:t)&&k("TotalViewTime",!1,t/1E3)});a.addEventListener(q.Player.PAUSE,function(){d.button.play.addClass(b.icons.play).removeClass(b.icons.pause);d.eventHandler.addClass(b.pointerEvents.none);0<r&&(t=Date.now()-
r+t,r=0);k("Pause",!0)});a.addEventListener(q.Player.ONLINE,function(){z=!1;d.noStreamerMessage.addClass(b.aok.hidden);d.stream.status.removeClass(b.icons.offline).addClass(b.icons.live)});a.addEventListener(q.Player.OFFLINE,function(){if(v<N-1){v++;var c=u[v];a.setChannel(c);d.stream.name.text(c);k("ChannelRotated",!1)}else z=!0,d.stream.status.removeClass(b.icons.live).addClass(b.icons.offline),x&&d.noStreamerMessage.removeClass(b.aok.hidden),k("ChannelOffline",!1)});return a}function J(c){function a(b){var e=
d.volume.slider.offset().left;b=Math.min(Math.max((Math.round(b-e)-f)/D,0),1);c.setVolume(b);c.getMuted()&&c.setMuted(!1);E(b)}var f=d.volume.thumb.width()/2;d.volume.slider.bind("mousedown",function(c){p=!0;a(c.clientX)});d.document.bind("mouseup focusout",e.debounce(function(){p&&(p=!1)},n.SMALL));d.document.bind("mousemove",e.debounce(function(c){p&&a(c.clientX)},n.MICRO));e.declarative("sisserouVolume","mouseenter mouseleave",function(c){p||d.volume.slider.toggleClass(b.aok.hidden,"mouseleave"===
c.type)});e.declarative("sisserouMuteUnmute","click",e.debounce(function(){var a=d.button.volume.hasClass(b.icons.volume);C(a,c)},n.MEDIUM))}function B(){var c=d.imageBlock&&d.imageBlock.height();c&&(d.sisserou.viewingWindowContainers.height(c),d.sisserou.viewingWindowContainers.width(c*O))}function C(c,a){a.setMuted(c);var b=a.getVolume();c||0!==b||(a.setVolume(.1),b=.1);E(c?0:b)}function E(c){d.button.volume.toggleClass(b.icons.volume,0!==c).toggleClass(b.icons.mute,0===c);c*=D;d.volume.thumb.css("margin-left",
c);d.volume.active.css("width",c)}function K(c){d.button.matureWarningAccept.click(function(){d.contentWarning.addClass(b.aok.hidden);y=!0;k("MatureWarningAccepted",!1);c.play()})}function k(c,a,b){c&&g.ue&&g.ue.count&&(b=b||1,c="sisserou"+c,a=a?g.ue.count(c)||0:0,g.ue.count(c,a+b))}var a=e.$,r=0,t=0,q=g.Twitch,m=e.state("sisserouPageState"),v=0,u;if(m&&m.channelId){u=m.channelIds?m.channelIds.split(","):[m.channelId];var N=u.length,M={twitchPlayerContainer:"sisserou-twitch-player-container"},d={imageBlock:a("#imageBlock"),
button:{matureWarningAccept:a("#mature-warning-accept"),play:a("#sisserou-play-toggle"),volume:a("#sisserou-volume-toggle")},contentWarning:a(".sisserou-content-warning"),document:a(document),eventHandler:a(".sisserou-event-handler"),sisserou:{expander:a(".sisserou-expander"),player:a(".sisserou-player"),viewingWindowContainers:a(".sisserou-viewing-window")},stream:{controls:a(".sisserou-stream-controls"),info:a(".sisserou-stream-info"),name:a(".sisserou-stream-name"),status:a(".sisserou-stream-status")},
volume:{active:a(".sisserou-volume-slider-active"),bar:a(".sisserou-volume-slider-bar"),slider:a(".sisserou-volume-slider"),thumb:a(".sisserou-volume-slider-thumb")},watchPrompt:a(".sisserou-watch-prompt"),noStreamerMessage:a(".sisserou-no-streamer")},b={aok:{hidden:"aok-hidden"},icons:{collapse:"sisserou-collapse-icon",expand:"sisserou-expand-icon",live:"sisserou-live-icon",mute:"sisserou-mute-icon",offline:"sisserou-offline-icon",pause:"sisserou-pause-icon",play:"sisserou-play-icon",volume:"sisserou-volume-icon"},
pointerEvents:{none:"pointer-events-none"}},n={MICRO:1,SMALL:10,MEDIUM:50,LARGE:100},O=16/9,D=d.volume.bar.width(),y=!1,p=!1,w=!1,x=!1,z=!1,A={playbackReportDropdown:"playback-report-reason",streamerReportDropdown:"streamer-report-reason"},G={button:{playbackReportSubmit:h("#playback-report-submit"),streamerReportSubmit:h("#streamer-report-submit")}},f={button:{playbackReportSubmit:a("#playback-report-submit"),streamerReportSubmit:a("#streamer-report-submit")},report:{menu:a(".sisserou-settings-menu"),
playbackConfirmation:a(".sisserou-playback-report-confirmation"),playbackMenu:a(".sisserou-playback-report-menu"),streamerConfirmation:a(".sisserou-streamer-report-confirmation"),streamerMenu:a(".sisserou-streamer-report-menu")},settings:a(".sisserou-settings")};H()}})});